# Generated by Django 4.2.30 on 2026-05-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_discount_alter_booking_id_alter_seat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
