# Generated by Django 4.2.30 on 2026-05-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_seat_reserved_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seat price',
                'verbose_name_plural': 'Seat price',
            },
        ),
    ]
