# Generated by Django 4.2.30 on 2026-05-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_seatprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatprice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
