# Generated by Django 4.2.30 on 2026-05-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_seatprice_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
        ),
    ]
