# Generated by Django 4.2.30 on 2026-05-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_movie_session_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('reserved', 'Reserved')], default='available', max_length=10)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='booking.seat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_statuses', to='booking.session')),
            ],
            options={
                'unique_together': {('seat', 'session')},
            },
        ),
    ]
