# Generated by Django 4.2.30 on 2026-05-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_seatstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='reserved_until',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='status',
        ),
    ]
